In [1]:
import torch

In [15]:
block_size = 8
tril = torch.tril(torch.ones(block_size, block_size))
tril

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
weight = torch.rand(size=(2, 8, 8))

In [25]:
weight[0, 0]

tensor([0.9594, 0.5737, 0.5985, 0.7875, 0.9830, 0.2920, 0.1491, 0.5450])

In [26]:
B,T,C = weight.shape

In [27]:
weight.masked_fill(tril[:T, :T] == 0, float('-inf'))

tensor([[[0.9594,   -inf,   -inf,   -inf,   -inf,   -inf,   -inf,   -inf],
         [0.6628, 0.3855,   -inf,   -inf,   -inf,   -inf,   -inf,   -inf],
         [0.0090, 0.3598, 0.5237,   -inf,   -inf,   -inf,   -inf,   -inf],
         [0.8371, 0.7451, 0.8327, 0.3730,   -inf,   -inf,   -inf,   -inf],
         [0.0197, 0.6828, 0.2064, 0.7634, 0.0088,   -inf,   -inf,   -inf],
         [0.6321, 0.1725, 0.2342, 0.5802, 0.3121, 0.1468,   -inf,   -inf],
         [0.6339, 0.7125, 0.5742, 0.2578, 0.0286, 0.0560, 0.3923,   -inf],
         [0.9295, 0.6487, 0.5281, 0.4590, 0.1221, 0.7831, 0.3138, 0.5677]],

        [[0.4897,   -inf,   -inf,   -inf,   -inf,   -inf,   -inf,   -inf],
         [0.1426, 0.1316,   -inf,   -inf,   -inf,   -inf,   -inf,   -inf],
         [0.8275, 0.2162, 0.2024,   -inf,   -inf,   -inf,   -inf,   -inf],
         [0.3062, 0.0743, 0.9803, 0.6994,   -inf,   -inf,   -inf,   -inf],
         [0.6355, 0.0366, 0.2125, 0.8169, 0.6259,   -inf,   -inf,   -inf],
         [0.6074, 0.724

In [1]:
import concurrent.futures
from functools import partial


In [9]:
lst = []

def add(number):
    return [n for n in range(number)]

if __name__ == "__main__":
    with concurrent.futures.ProcessPoolExecutor() as executor:
        results = executor.map(add, range(3))
        for result in results:
            print(result)
        
lst

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

[]